### ISSUE TITLE
[Bug] NFT wallet broken

### ISSUE THREAD

**Issue by Amplificator** [Chia-Network/chia-blockchain#14395]
### What happened?

I have somehow gotten an issue where my NFTs seems to have disappeared due to what looks like a broken NFT wallet. With the help of someone, we found out that I actually still own the wallet addresses they are in.

When running "chia wallet show" it will show that I'm fully synced and then continue to list the Chia Wallet and Pool Wallet just fine but then throws an error as soon as it gets to the NFT Wallet - this wallet seems to be.. broken for me and I assume that's why the GUI also isn't showing any NFTs?
On one machine I have also cleared databases (wallet db and blockchain db) along with config.yaml, basically clearing everything out that I can. I then resynced to see if that would have fixed it, but it did not.
I also tried setting up a new virtual machine with only Chia on it, nothing else installed and gives the same result so it doesn't appear to be a local problem on a single machine.

What I did in the weeks before this issue was to enable both DataLayer and Wallet Connect but never actually used them so I disabled both again. Days later I created offers for these NFTs but also cancelled those. I verified that the offer section reported that the cancellations had been confirmed so I know they didn't go anywhere (and as stated above, we verified that I actually still do own them).
But after cancelling the NFTs they simply disappeared from the GUI, so I assume somewhere along the line the issue with the NFT wallet happened and the GUI simply can't show them.

The GUI throws no errors, but running "chia wallet show" on the command line will result in the error above.

Any suggestions on what exactly happened and how to fix it?

The output of "chia wallet show" is attached.

### Version

1.6.2

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
Exception from 'wallet' {'error': '3', 'success': False}:
Traceback (most recent call last):
File "chia/cmds/cmds_[util.py](http://util.py/)", line 100, in get_any_service_client
File "chia/cmds/cmds_[util.py](http://util.py/)", line 211, in execute_with_wallet
File "chia/cmds/wallet_[funcs.py](http://funcs.py/)", line 752, in print_balances
File "chia/rpc/wallet_rpc_[client.py](http://client.py/)", line 100, in get_wallet_balance
File "chia/rpc/rpc_[client.py](http://client.py/)", line 50, in fetch
ValueError: {'error': '3', 'success': False}
```

**Comment by MumfMeisterT** [comment]
How have you been installing Chia? Are you using the .deb files or pulling down from clone, etc?
Could you please post for us the entire logs with this error in it?

**Comment by Amplificator** [comment]
On Windows I used the official download from chia.net and on AlmaLinux I used the rpm, also from chia.net - I did not build from source.

**Comment by Amplificator** [comment]
Alright, here's a clean debug.log file: https://paste.centos.org/view/8f76499f

The steps I did was to close Chia. Then delete the old debug.log as it was several megabytes already. Started Chia GUI up and let it sync. When it was fully synced I clicked on the NFT button on the left. I then also ran "chia wallet show" which produced the error I mentioned earlier. After that I closed Chia and used fpaste to upload the debug.log file above.

**Comment by Amplificator** [comment]
Here's the above log, since the link above will expire soon:

```
2023-01-26T23:43:53.038 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 3
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1065, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1496, in coin_added
  File "chia/wallet/wallet_state_manager.py", line 1738, in convert_puzzle_hash
KeyError: 3
2023-01-26T23:43:53.348 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 3
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1034, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 644, in determine_coin_type
  File "chia/wallet/wallet_state_manager.py", line 935, in handle_nft
KeyError: 3
2023-01-26T23:43:54.585 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 3
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1034, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 644, in determine_coin_type
  File "chia/wallet/wallet_state_manager.py", line 935, in handle_nft
KeyError: 3
2023-01-26T23:43:56.220 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 3
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1034, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 644, in determine_coin_type
  File "chia/wallet/wallet_state_manager.py", line 935, in handle_nft
KeyError: 3
2023-01-26T23:43:57.648 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 3
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1034, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 644, in determine_coin_type
  File "chia/wallet/wallet_state_manager.py", line 935, in handle_nft
KeyError: 3
2023-01-26T23:44:01.813 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 329, in safe_handle
  File "chia/rpc/rpc_server.py", line 320, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 2317, in nft_get_wallet_did
KeyError: 3

2023-01-26T23:44:05.773 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 329, in safe_handle
  File "chia/rpc/rpc_server.py", line 320, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 2188, in nft_get_nfts
KeyError: 3

2023-01-26T23:44:17.191 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/util.py", line 18, in inner
  File "chia/rpc/wallet_rpc_api.py", line 767, in get_wallet_balance
KeyError: 3

2023-01-26T23:44:18.542 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 3
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1121, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1738, in convert_puzzle_hash
KeyError: 3
2023-01-26T23:44:18.746 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 3
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1121, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1738, in convert_puzzle_hash
KeyError: 3
2023-01-26T23:44:18.942 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 3
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1121, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1738, in convert_puzzle_hash
KeyError: 3
```

**Comment by Amplificator** [comment]
Issue is still there with 1.7.0

**Comment by stultuszoombie** [comment]
> Issue is still there with 1.7.0

https://github.com/Chia-Network/chia-blockchain/issues/14279#issuecomment-1427181352
here are all errors that i have from 1.6.2

**Comment by aqk** [comment]
Thank you very much for your report.

We recently fixed an issue where an older DID on chain would be detected as invalid, and would interrupt the creation of the DID wallet when the client hears about it.

That particular issue is fixed in 1.8.0-b2:

https://github.com/Chia-Network/chia-blockchain/releases/tag/1.8.0-b2


Here's how to test it:


## Set your logging level to DEBUG

## Make sure that chia is completely stopped.
```bash
chia stop -d all
```

## Back up your wallet database
```bash
mkdir ~/chia-wallet-db-backup-2023-feb-28
cp -R ~/.chia/mainnet/wallet/db/* ~/chia-wallet-db-backup-2023-feb-28
```

## Remove your old wallet database
```bash
rm ~/.chia/mainnet/wallet/db/*
```

## Install the new version of Chia
https://github.com/Chia-Network/chia-blockchain/releases/tag/1.8.0-b2


## Set your logging level to DEBUG

## Start Chia again and wait for it to sync
```
chia start wallet
chia wallet show
```

## After sync, run the wallet DB check tool:
`chia wallet check`

Let us know how it goes! We'd appreciate seeing your logfiles (`debug.log*`) if there is still an issue.

**Comment by aqk** [comment]
Thank you very much for your report.

We recently fixed an issue where an older DID on chain would be detected as invalid, and would interrupt the creation of the DID wallet when the client hears about it.

That particular issue is fixed in 1.8.0-b2:

https://github.com/Chia-Network/chia-blockchain/releases/tag/1.8.0-b2


Here's how to test it:


## Set your logging level to DEBUG

## Make sure that chia is completely stopped.
```bash
chia stop -d all
```

## Back up your wallet database
```bash
mkdir ~/chia-wallet-db-backup-2023-feb-28
cp -R ~/.chia/mainnet/wallet/db/* ~/chia-wallet-db-backup-2023-feb-28
```

## Remove your old wallet database
```bash
rm ~/.chia/mainnet/wallet/db/*
```

## Install the new version of Chia
https://github.com/Chia-Network/chia-blockchain/releases/tag/1.8.0-b2


## Set your logging level to DEBUG

## Start Chia again and wait for it to sync
```
chia start wallet
chia wallet show
```

## After sync, run the wallet DB check tool:
`chia wallet check`

Let us know how it goes! We'd appreciate seeing your logfiles (`debug.log*`) if there is still an issue.

**Comment by stultuszoombie** [comment]
> Thank you very much for your report.
> 
> We recently fixed an issue where an older DID on chain would be detected as invalid, and would interrupt the creation of the DID wallet when the client hears about it.
> 
> That particular issue is fixed in 1.8.0-b2:
> 
> https://github.com/Chia-Network/chia-blockchain/releases/tag/1.8.0-b2
> 
> Here's how to test it:
> 
> ## Set your logging level to DEBUG
> ## Make sure that chia is completely stopped.
> ```shell
> chia stop -d all
> ```
> 
> ## Back up your wallet database
> ```shell
> mkdir ~/chia-wallet-db-backup-2023-feb-28
> cp -R ~/.chia/mainnet/wallet/db/* ~/chia-wallet-db-backup-2023-feb-28
> ```
> 
> ## Remove your old wallet database
> ```shell
> rm ~/.chia/mainnet/wallet/db/*
> ```
> 
> ## Install the new version of Chia
> https://github.com/Chia-Network/chia-blockchain/releases/tag/1.8.0-b2
> 
> ## Set your logging level to DEBUG
> ## Start Chia again and wait for it to sync
> ```
> chia start wallet
> chia wallet show
> ```
> 
> ## After sync, run the wallet DB check tool:
> `chia wallet check`
> 
> Let us know how it goes! We'd appreciate seeing your logfiles (`debug.log*`) if there is still an issue.

![image](https://user-images.githubusercontent.com/61159243/222918531-466d8bfe-f5ae-40fa-b4b1-1467839e54f8.png)
i have done clean install, on a clean pc with windows (the old release with db are on another pc that it's off), i only trasferred full_node db, and keyring;
i don't know if it can be important but full_node id has changed from: 
 dad25f2...... to 11205ba......
 the did that's not mine is appeared again:
 
![image](https://user-images.githubusercontent.com/61159243/222918991-56a329c2-43aa-4207-ab67-52673ca42d6a.png)

without DID:ID:

now i run command chia wallet check

**Comment by stultuszoombie** [comment]
@aqk 
this is debug log after wallet check
i run full_node also, because light wallet in stand_alone mode is very slow:
[chia wallet check.log](https://github.com/Chia-Network/chia-blockchain/files/10889267/chia.wallet.check.log)
i have also abou 300 MB (debug mode when is syncing) from genesis

**Comment by stultuszoombie** [comment]
@aqk 
**### GUI WIN on 1.8.0-b2**
![wallet broken pre_release](https://user-images.githubusercontent.com/61159243/222929384-7f70b9dd-b28e-4739-9d28-46fbd1a27f09.png)
when "manage tokens" the side-bar (as 1.7) don't scroll, until you close and reopen

![issue1_8_pre_r](https://user-images.githubusercontent.com/61159243/222929559-41ee9d19-6dfc-4c5d-b561-cd4a22dc600f.png)
derivation index is lower than 1.7 (red circle) i have up to 2000
names of cat's  do they still need to be entered manually?
after few hours that wallet is completely synced, from 126 nft now are 96
(this messages are in real-time)
![image](https://user-images.githubusercontent.com/61159243/222929902-209529c8-c76b-451e-a292-6d93ff7c0880.png)
yellow mark nft wallet with did not mine (chia_ndroids)
light-blue empty
purple lost did in 1.6.2 and 1.7 but is empty
![image](https://user-images.githubusercontent.com/61159243/222930414-159e3450-2fd5-4ea8-ba59-b551a29807bf.png)
now i close this wallet and open another wallet generated from this master_key
after full_sync, i add other issues....

**Comment by Amplificator** [comment]
My original issue is still not fixed. I tried with both 1.8.0b2 and 1.8.0b3.

I get this in the debug.log:

```
2023-03-04T23:48:27.808 wallet wallet                     : WARNING  Starting service wallet ...
2023-03-04T23:48:29.058 wallet wallet                     : WARNING  Started wallet service on network_id: mainnet at port 8449
2023-03-04T23:49:56.303 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 4
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1109, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1560, in coin_added
KeyError: 4
2023-03-04T23:50:09.677 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 4
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1109, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1560, in coin_added
KeyError: 4
2023-03-04T23:50:10.068 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 4
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1109, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1560, in coin_added
KeyError: 4
2023-03-04T23:50:10.471 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 4
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1109, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1537, in coin_added
  File "chia/wallet/wallet_state_manager.py", line 1808, in convert_puzzle_hash
KeyError: 4
2023-03-04T23:50:11.025 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 4
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1224, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1808, in convert_puzzle_hash
KeyError: 4
2023-03-04T23:51:00.016 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 4
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1109, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1560, in coin_added
KeyError: 4
2023-03-04T23:51:37.482 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 4
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1109, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1560, in coin_added
KeyError: 4
2023-03-04T23:51:40.574 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 4
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1224, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1808, in convert_puzzle_hash
KeyError: 4
2023-03-04T23:51:41.053 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 4
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1109, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1537, in coin_added
  File "chia/wallet/wallet_state_manager.py", line 1808, in convert_puzzle_hash
KeyError: 4
2023-03-04T23:51:41.525 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 4
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1109, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1560, in coin_added
KeyError: 4
2023-03-04T23:51:41.997 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 4
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1109, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1560, in coin_added
KeyError: 4
2023-03-04T23:52:25.583 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... 4
Traceback (most recent call last):
  File "chia/wallet/wallet_state_manager.py", line 1109, in new_coin_state
  File "chia/wallet/wallet_state_manager.py", line 1560, in coin_added
KeyError: 4
```

The NFT page just shows the loading icon all the time.

**Comment by stultuszoombie** [comment]
> @aqk **### GUI WIN on 1.8.0-b2** ![wallet broken pre_release](https://user-images.githubusercontent.com/61159243/222929384-7f70b9dd-b28e-4739-9d28-46fbd1a27f09.png) when "manage tokens" the side-bar (as 1.7) don't scroll, until you close and reopen
> 
> ![issue1_8_pre_r](https://user-images.githubusercontent.com/61159243/222929559-41ee9d19-6dfc-4c5d-b561-cd4a22dc600f.png) derivation index is lower than 1.7 (red circle) i have up to 2000 names of cat's do they still need to be entered manually? after few hours that wallet is completely synced, from 126 nft now are 96 (this messages are in real-time) ![image](https://user-images.githubusercontent.com/61159243/222929902-209529c8-c76b-451e-a292-6d93ff7c0880.png) yellow mark nft wallet with did not mine (chia_ndroids) light-blue empty (in version before 1.6.2 if was empty don't appear in gui) purple lost did in 1.6.2 and 1.7 but is empty ![image](https://user-images.githubusercontent.com/61159243/222930414-159e3450-2fd5-4ea8-ba59-b551a29807bf.png) now i close this wallet and open another wallet generated from this master_key after full_sync, i add other issues....
### from 105 NFTs to 92.... but.....
![image](https://user-images.githubusercontent.com/61159243/222932252-6b21409e-febd-4b5d-82f0-d880cde7e2d7.png)
![image](https://user-images.githubusercontent.com/61159243/222932266-c843c96d-63c9-4ac0-8ffb-7edd4b73f22c.png)
![image](https://user-images.githubusercontent.com/61159243/222932275-e16ed070-6ce7-4a5e-b696-72723ff695ae.png)

**Comment by Amplificator** [comment]
Just an update: It's still present in 1.7.1

**Comment by emlowe** [comment]
Closing old issue we believe originally resolved in 1.8.0 - can be reopened if problems persist
