### ISSUE TITLE
[Bug] - Can't join pool

### ISSUE THREAD

**Issue by abwqr** [Chia-Network/chia-blockchain#18431]
### **What happened?**

When attempting to join a pool using the GUI with the "Self Pool" or  "Connect to pool" option, the process encounters an issue where the state reverts to "Join a Pool" after the transaction is confirmed. Below are the details of the observed behavior and steps to reproduce the issue.

### **Supporting Evidence:**

**1. Waiting for transaction to be completed**
<img width="1407" alt="Screenshot 2024-08-09 at 11 29 03 AM" src="https://github.com/user-attachments/assets/064cf635-3446-4bd5-baea-13446ec7913b">

**2. Transaction is confirmed**
<img width="1023" alt="Screenshot 2024-08-09 at 10 09 50 AM" src="https://github.com/user-attachments/assets/313d2013-9b98-42ca-9a19-3a29ab59c4a0">

**3. No new pools are shown**
<img width="1021" alt="Screenshot 2024-08-09 at 11 30 26 AM" src="https://github.com/user-attachments/assets/39628153-e4b5-41aa-b8b6-0d5c7c1d0f8e">

**4. Pools listed in CLI**
<img width="1466" alt="Screenshot 2024-08-15 at 9 48 04 AM" src="https://github.com/user-attachments/assets/54b0f85a-7069-4964-9be3-a7e3942b111c">

### **Affected Test Cases**
Test case 6 - Can you generate a plot nft? 
Test case 7 - Can you generate plots?
Test case 8 - Can you join a pool?
Test case 9 - Can you leave a pool?
Test case 10 - Can you claim rewards for self-pooling?

### Version

2.4.3-rc1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output
<img width="1461" alt="Screenshot 2024-08-15 at 9 55 11 AM" src="https://github.com/user-attachments/assets/131d4362-9dd2-41f1-8109-b799a01fe944">

Pool is created without errors

_No response_

**Comment by BrandtH22** [comment]
Hey @abwqr , did you have any other wallets on the same machine when performing these steps?
I am wondering if this is related to https://github.com/Chia-Network/chia-blockchain/issues/18396 . Essentially if you have another wallet that has no transactions then this issue might already be resolved with https://github.com/Chia-Network/chia-blockchain/pull/18405

**Comment by BrandtH22** [comment]
Hey @abwqr , I have attempted to reproduce in rc3 to no avail and believe this issue is now fixed.

Can you attempt to reproduce in rc3 with INFO logs? If the issue persists please add that information tot his ticket, if it does not please close the ticket.

**Comment by abwqr** [comment]
@BrandtH22 I have updated the ticket. The issue persists in rc3, upon furthering debugging I found out that the pools are created (can be seen in "4. Pools listed in CLI") but they aren't visible on the GUI.

**Comment by BrandtH22** [comment]
Hey @abwqr , I am still not able to reproduce this locally, can you provide INFO logs from the reproduced issue on rc3? 

Also when reproducing please first ensure that you have deleted the wallet dbs prior to syncing with rc3 to ensure there are no left over issues from the rc1 bug. Let me know if you have any questions and thank you for the information!

**Comment by chia-rschmidt** [comment]
Saw this issue on RC3 Ubuntu 22.04. Attached is the log. Plot NFT would only show up after restarting the GUI.
[TC-Golf.log](https://github.com/user-attachments/files/16652440/TC-Golf.log)

**Comment by BrandtH22** [comment]
Hey @chia-rschmidt , those logs indicate a number of other issues that could lead to the plotNFT not appearing which are unrelated to the chia software itself (such as inability to query DNS introducers indicating a networking issue).

Since I am still not able to reproduce this locally, can you provide INFO logs from the reproduced issue on rc3?

Also when reproducing please first ensure that you have deleted the wallet dbs prior to syncing with rc3 to ensure there are no left over issues from the rc1 bug. Let me know if you have any questions and thank you for the information!
