### ISSUE TITLE
Caught plotting error: bad allocation

### ISSUE THREAD

**Issue by hardhub** [Chia-Network/chia-blockchain#3442]
Starting phase 1/4: Forward Propagation into tmp files... Sun May  2 19:03:52 2021
Computing table 1
F1 complete, time: 293.682 seconds. CPU (221.09%) Sun May  2 19:08:45 2021
Computing table 2
Caught plotting error: bad allocation
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation
[5076] Failed to execute script chia

It is on Windows only if many parallel processes are running. 
Disk space is enough, RAM is enough. RAM is not broken (but I will test more).  
Swap is totally absent because not needed (a lot of RAM).
Some n first processes started and work good (no errors).
But next one fails on computing tables.

Are you sure it is hardware issue and not software bug?

OS: Windows 7 x64

**Comment by hardhub** [comment]
It is 100% not hardware issue.  
When I created pagefile the same size as RAM then new process started and tables are computed.

But it is not normal because there is at least half of RAM was available.  
It is most likely some bug with chia or python bundled with chia.

**Comment by gromran** [comment]
> Swap is totally absent because not needed.

Because you don't understand, how this work.

**Comment by hardhub** [comment]
> 
> 
> > Swap is totally absent because not needed.
> 
> Because you don't understand, how this work.
> Many Apps crash, when swap is disabled.

Seriously? LOL, I hope you are not related to chia implementation ))

**Comment by mario-mlc** [comment]
Same error on trying to plot with 3072MB of RAM, single thread, Celeron N2830 (2-core), 4GB RAM total, Ubuntu 18 LTS. Seems to keep on advancing, though... old and low profile hardware seem to take a week on these conditions...

**Comment by ansonlianson** [comment]
I find that a lot of these cases are because they plotting files while mining ETH; And once I plug in and thunderbolt dock and reboot the computer, I can't plot 4 files at the same time(which i can easily make it before reboot, even 5). So i guess the "bad allocation" report is due to the lack of bandwidth, like the bandwidth of PCIE

**Comment by hardhub** [comment]
> 
> 
> I find that a lot of these cases are because they plotting files while mining ETH; And once I plug in and thunderbolt dock and reboot the computer, I can't plot 4 files at the same time(which i can easily make it before reboot, even 5). So i guess the "bad allocation" report is due to the lack of bandwidth, like the bandwidth of PCIE

Obviously it is not current issue.

1) It is just plotting with keys in command line.
2) It was solved by adding pagefile (even if half of RAM was available).

**Comment by Ratzoletto** [comment]
> > I find that a lot of these cases are because they plotting files while mining ETH; And once I plug in and thunderbolt dock and reboot the computer, I can't plot 4 files at the same time(which i can easily make it before reboot, even 5). So i guess the "bad allocation" report is due to the lack of bandwidth, like the bandwidth of PCIE
> 
> Obviously it is not current issue.
> 
> 1. It is just plotting with keys in command line.
> 2. It was solved (just workaround) by adding pagefile (even if half of RAM was available).


Problem is solved? Dosen't sound to me like it is solved...


`Starting phase 3/4: Compression from tmp files into "D:\\Plot\\plot-k32-2021-05-13-00-59-f65483823ac3e2143bf126c9c569f54a4019d1defea83442bc11ea9c52032ec2.plot.2.tmp" ... Thu May 13 06:51:44 2021
Compressing tables 1 and 2
Caught plotting error: bad allocation
[22100] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation`

**Comment by hardhub** [comment]
> 
> Problem is solved? Dosen't sound to me like it is solved...
> 

No, it is definitely not solved. But it can be workaround by adding page file.  
For some reason chia cannot allocate physical memory and needs page file.  
I even do not know exactly if it is chia-specific issue or general one.  
I fully switched to Linux, so for me it is not actual anymore.  
But sure something exists somewhere ))

**Comment by fullet-tortuga** [comment]
I'm afraid gromran is right about the swap file. I've verified many times that some applications need the swap file to be there, even if it's a ridiculous 8MB one, or they crash badly just because. It's sad but it's true. Take it from another guy who also hates swapping to disk something that could be just be done in memory :-P

**Comment by tommy1735** [comment]
today first time i got it too:
```
Forward propagation table time: 1584.211 seconds. CPU (141.700%) Fri May 14 19:16:09 2021
Time for phase 1 = 9302.728 seconds. CPU (144.340%) Fri May 14 19:16:09 2021

Starting phase 2/4: Backpropagation into tmp files... Fri May 14 19:16:09 2021
Backpropagating on table 7
scanned table 7
scanned time =  23.922 seconds. CPU (76.810%) Fri May 14 19:16:33 2021
sorting table 7
Backpropagating on table 6
scanned table 6
scanned time =  185.441 seconds. CPU (99.390%) Fri May 14 19:22:14 2021
sorting table 6
sort time =  710.625 seconds. CPU (99.080%) Fri May 14 19:34:05 2021
Backpropagating on table 5
scanned table 5
scanned time =  183.851 seconds. CPU (98.950%) Fri May 14 19:37:09 2021
sorting table 5
sort time =  664.098 seconds. CPU (99.710%) Fri May 14 19:48:13 2021
Backpropagating on table 4
scanned table 4
scanned time =  186.382 seconds. CPU (99.250%) Fri May 14 19:51:20 2021
sorting table 4
sort time =  682.238 seconds. CPU (99.470%) Fri May 14 20:02:42 2021
Backpropagating on table 3
scanned table 3
scanned time =  189.696 seconds. CPU (98.910%) Fri May 14 20:05:52 2021
sorting table 3
Caught plotting error: bad allocation
[5100] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation
```
i was plotting 8 parallel 4 to each nvme ssd... error was on MP600 2 TB PCIE 4 was doing 6 before with no problem
only reason of error i cant think of is i OCed my Ryzen 7 5800x a bit more
also in hwinfo64 i can see "Virtual Memory Load" is at 90% and was max at 99% but Physical Memory (48GB) was maxed at 58% only.  https://prnt.sc/12xns8a looks like my page file is too small too

**Comment by trif55** [comment]
I've just had it a few times, going above 12 parallel on my Ryzen 3900X while gaming seemed a stretch too far, CPU was hitting 100% rarely but it seemed to cause this "Caught plotting error: bad allocation" error still, I've got 96GB ram that's still only 50% used, SSD IO was nearing 100% but that shouldn't cause errors?
