### ISSUE TITLE
[BUG] Node not syncing, when node syncs wallet doesn't sync.

### ISSUE THREAD

**Issue by boner-cmd** [Chia-Network/chia-blockchain#5914]
Upgraded to 1.1.6. Node synced, but wallet not syncing.

![image](https://user-images.githubusercontent.com/54084132/119293042-3e465b00-bc17-11eb-96c8-127479ab13e5.png)

- OS: Linux
- OS Version/Flavor: Kubuntu 20.04
- CPU: AMD 2600

Been having these issues (node not syncing or wallet not syncing) since at least 1.1.3 if not 1.1.2.  Node sometimes has 0 connections until I add one manually, which is still sometimes very slow or will not result in more connections. 

I finally finished plotting so that's no longer a factor, _even though it never should have been_. Now I am just trying to farm and my node just doesn't sync, and when it does sync, I get issues like wallet syncing.

![image](https://user-images.githubusercontent.com/54084132/119295195-d2b2bc80-bc1b-11eb-8649-1ab566f975e8.png)

Yes, I have many connected nodes. Yes, port 8444 is forwarded. Yes, I have used the port checker to confirm that. Yes, I have deleted my .config directory and regenerated it.

**Comment by boner-cmd** [comment]
Nothing like investing a lot of time in plotting and farming only to find out that with a time-to-win that increases in *months* that whole days of chances are being missed due to sync issues.

**Comment by lvpcguru** [comment]
First anything in your .chia\mainnet\log\debug.log file related to the wallet?

You have your port 8444 forwarded correctly? After all the 1.1.6 fixes to syncing that is a common issue.

I couldnt get my wallet to sync at all and realized I had NATed my outbound as well.  8444 inbound let the blockchain sync but the wallet was messed up and was connecting out on 8444 as well. I had a lot of those 8444/8444 ports connections like you do. They have all gone away after I fixed the NAT policy to only go one way and restarted. 

I did delete my wallet db during troubleshooting but I dont know if that had any effect.

**Comment by siaarzh** [comment]
Duplicate of #3298

See https://github.com/Chia-Network/chia-blockchain/issues/3298#issuecomment-845414120, https://github.com/Chia-Network/chia-blockchain/issues/3298#issuecomment-830738275 for possible solutions

**Comment by boner-cmd** [comment]
I'm not using the GUI. No errors in debug. Will check solutions to confirm.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by lvpcguru** [comment]
Any luck @boner-cmd

**Comment by boner-cmd** [comment]
One comment is adding nodes directly, this doesn't fix the issue. The other is deleting the peer table, which I also have tried; I actually delete the whole .chia folder when I do this. This is how I get the *node* synced again, but so far has not un-stuck my wallet. It's also very time-consuming to test since I am red-downloading the whole chain each time. I can try targeting the peer db itself to make that faster, which is a good suggestion, but again this is something I already do.

To clarify- deleting my whole .chia folder is how I forced my node to sync. However, my wallet is still stuck.
________________________________

**Comment by boner-cmd** [comment]
Wallet still takes forever or doesn't sync. Same issue. Deleted everything and started over. Node synced up. Wallet still not synced.

**Comment by engine-off** [comment]
That fact that this issue seems to still be ongoing suggests to me that the devs have already realised that chia is basically dead in the water and not worth the trouble.

**Comment by mariano54** [comment]
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue. We are consolidating all wallet connection and sync issues there.
