### ISSUE TITLE
Plenty of "ProtocolMessageTypes" errors and warnings, every 2nd minute

### ISSUE THREAD

**Issue by Kikicaj** [Chia-Network/chia-blockchain#7064]
Windows 10, 1.1.7
Started to appear since yesterday (more than 24h ago already)
causing overall SP and lookups delays
not farming any forks, could it be caused by peer connected farming a fork?

```
21-06-30T07:58:28.295 full_node chia.server.rate_limits : WARNING  Invalid message: 2, 2 is not a valid ProtocolMessageTypes
2021-06-30T07:58:28.482 full_node full_node_server        : INFO     Connection closed: 45.248.15.167, node id: 03f91e655b89f67bcd4607a1dcd627f59511e06925c6276cb0289d2ff7c021a3
2021-06-30T07:58:28.482 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '45.248.15.167', 'port': 56737}
2021-06-30T07:58:28.482 full_node full_node_server        : ERROR    Exception 2 is not a valid ProtocolMessageTypes, exception Stack: ValueError: 2 is not a valid ProtocolMessageTypes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\server\server.py", line 254, in incoming_connection
  File "chia\server\ws_connection.py", line 142, in perform_handshake
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\enum.py", line 315, in __call__
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\enum.py", line 569, in __new__
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\enum.py", line 553, in __new__
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\enum.py", line 582, in _missing_
ValueError: 2 is not a valid ProtocolMessageTypes

2021-06-30T07:58:31.810 full_node full_node_server        : INFO     Connected with full_node {'host': '216.228.50.184', 'port': 8444}
2021-06-30T07:58:31.810 full_node full_node_server        : INFO     Connection closed: 216.228.50.184, node id: c0b4e6af1c0d2ab5c72cb22407b6b15552ce82501f022e8b92ba555f9f3706b2
2021-06-30T07:58:31.810 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '216.228.50.184', 'port': 8444}
```

**Comment by chehlvs** [comment]
Same for me. I raised this issue as well. As well no forks farming. Issue appeared 2 days ago.

https://github.com/Chia-Network/chia-blockchain/issues/7062

Since weeks system was working stable, so I do not changed something on my side.

**Comment by emlowe** [comment]
It would be helpful for a debug log as well - right now we believe this is caused by some unexpected/unknown peer.

**Comment by emlowe** [comment]
I've received some debug logs from a few parties. I've also been informed that at least one fork (Rose) is using handshake protocol==2 which would for sure cause this issue.

**Comment by hoffmang9** [comment]
Fixed in 1.2.0

**Comment by ajie1015** [comment]
> Fixed in 1.2.0

when i upgrade to 1.2.0 .simulate issue  happened . when i rollback to the 1.1.7 issue fixed . and i have check both  harvester and full node both are 1.2.0 when issue happened .

2021-07-10T21:54:01.580 harvester chia.server.rate_limits : WARNING  Invalid message: 67, 67 is not a valid ProtocolMessageTypes
2021-07-10T21:54:01.582 harvester harvester_server        : ERROR    Exception: 67 is not a valid ProtocolMessageTypes <class 'ValueError'>, closing connection {'host': '192.168.1.2', 'port': 8447}. ValueError: 67 is not a valid ProtocolMessageTypes

**Comment by iMAGiCJAKE** [comment]
still got same issue on 1.2.1 also 1.2.2

**Comment by myITToolBox** [comment]
Also seeing these on 1.2.2

```
2021-07-15T12:26:50.420 harvester harvester_server        : ERROR    Exception: 67 is not a valid ProtocolMessageTypes <class 'ValueError'>, closing connection {'host': '192.168.0.xxx', 'port': 8447}. Traceback (most recent call last):
  File "/home/behlinga/chia-blockchain/chia/server/server.py", line 493, in api_call
    f"<- {ProtocolMessageTypes(full_message.type).name} from peer "
  File "/usr/lib/python3.9/enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.9/enum.py", line 678, in __new__
    raise ve_exc
ValueError: 67 is not a valid ProtocolMessageTypes

```

**Comment by iMAGiCJAKE** [comment]
Is this error that people need to worry? why don't mention about the error? and it still happened on 1.2.6 randomly and frequently
